library(knitr)
library(tidyverse)
library(httr)
library(jsonlite)
library(plotly)
library(patchwork)
library(cowplot)
library(network)
library(ggraph)
library(networkDynamic)
library(ndtv)
library(tsna)

install.packages("patchwork", "cowplot", "network", "ggraph", "networkDynamic", "ndtv", "tsna")
